### ISSUE TITLE
[New Idea] Getter setter should be added for useState - [useReqState]

### ISSUE THREAD

**Issue by xXAvoraXx** [alibaba/hooks#1487] opened 2022-03-04 16:17 UTC
Getter setter should be added for useState.
For example, where I use the state variable, if its value is empty, it should send a request to the api. However, this may cause it to send the same request more than once in duplicate components.

For example, when we normally assign a value to a state variable by request, we use the following structure.

```
const [state, setState] = useState();

const { run } = useRequest(getStateValue, {
    onSuccess:(data) => {
        setState(data);
    }
});

useEffect(() => {
   run();
}, [])
```
In some cases we use the same state variable in other pages, it's pointless to repeat this code for each page.
For example, when using the ant design useModel hook, if the data is empty, I have to put this code at the beginning of the pages I need. Instead of doing all this, when I just call the state variable, the code should do it without background conflict, it should not send it again if a request has been sent before, it should call it from there if the state value is filled.

useReqState

**Comment by brickspert** [comment] 2022-03-07 03:04
```ts
const { data,  run } = useRequest(getStateValue, {
    onSuccess:(data) => {
        setState(data);
    }
});

const result = new Proxy({
    data,  
}, {
    get: function(obj, prop) {
      if(!obj.prop){
        run();
    }
  }
})
```

like this?

**Comment by xXAvoraXx** [comment] 2022-03-07 14:10
> ```ts
> const { data,  run } = useRequest(getStateValue, {
>     onSuccess:(data) => {
>         setState(data);
>     }
> });
> 
> const result = new Proxy({
>     data,  
> }, {
>     get: function(obj, prop) {
>       if(!obj.prop){
>         run();
>     }
>   }
> })
> ```
> 
> like this?

Yes it seems logical, but there is a problem that nested mapped components using the same state variable will always be forwarding the same request to the api.

If I had to create a scenario it would be like this,

**useMode**l is a **UmiJs** hook.
```
export const Child = () => {
  const {result} = useModel('state');

  return 
    (<div>
      {result.value}
    </div>)
}

export const Parent = () => {
  const {mapEntityData} = useModel('otherState');

 return(
   mapEntityDaya.map((m) => {
        return <Child entity={m}/>
    })
  )
}
```
As a result of the scenario, there will be a problem when the components are rendering.
For example, there are 5 child components,

> Child[0] rendering... -> result request to api.
> Child[1] rendering... -> result request to api.
> Child[2] rendering... -> result request to api.
> Child[3] rendering... -> result request to api.
> Child[4] rendering... -> result request to api.

Because they all happen at the same time, only one of them needs to send a request.

The behavior should be like this:

> Child[0] rendering... -> result request to api.
> Child[1] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
> Child[2] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
> Child[3] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
> Child[4] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.

If this useReqState hook is developed, a very important code duplication issue will be resolved.

**The pros of this hook are:**

1. In multiple different or same components requesting a state variable, there is no need to check if the requested state is empty with useEffect during render and request it from the api if it is empty.
2. Code duplication is avoided.

**[1]**
```
useEffect(()=> {
 if(state == null){
    run();
 }
}, [])
```

**[2]**
Page1.tsx needs the state variable.
```
const {state} = useModel('state');
useEffect(()=> {
 if(state == null){
    run();
 }
}, [])
```
**Page2.tsx** needs the state variable.
It needs the same state variable on **Page2.tsx**
```
const {state} = useModel('state');
useEffect(()=> {
 if(state == null){
    run();
 }
}, [])
```
As you can see, code duplication has occurred.

**How should the hook be used?**

```
export default () => { // --> useModel('state') 
   const {state, loadingState} = useReqState('maybe link parameters or request method params'); // extend with request properties

  return{
   state,
   loadingState
  }
}

export const TestComponent = () => {
  const {state, loadingState} = useModel('state');
  
 return {
    <Spin loading={loadingState}>{state}</Spin>
  }
}

```

**Comment by xXAvoraXx** [comment] 2022-03-10 22:11
Is there any update ? @brickspert

**Comment by brickspert** [comment] 2022-03-11 09:40
I understand what you mean, but I don't have a good solution.

There have two problem: 

1.  Multiple calls, only one request is actually sent, like this

```
Child[0] rendering... -> result request to api.
Child[1] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
Child[2] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
Child[3] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
Child[4] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
```
This can be resolved by useRequest **options.cacheKey**.

2. Check whether it is empty before each use.

```ts
const {state} = useModel('state');
useEffect(()=> {
 if(state == null){
    run();
 }
}, [])
```

This problem is more of an engineering problem, caused by the mechanism of useModel, not a general problem.

The useModel's model is initialized when the application mount, not when it is needed, which causes this problem.

If you use other solutions such as context, there will be no problem.

So this problem is not a general problem, ahooks should not have similar hooks.

**Comment by xXAvoraXx** [comment] 2022-03-11 11:21
> I understand what you mean, but I don't have a good solution.
> 
> There have two problem:
> 
> 1. Multiple calls, only one request is actually sent, like this
> 
> ```
> Child[0] rendering... -> result request to api.
> Child[1] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
> Child[2] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
> Child[3] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
> Child[4] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
> ```
> 
> This can be resolved by useRequest **options.cacheKey**.
> 
> 2. Check whether it is empty before each use.
> 
> ```ts
> const {state} = useModel('state');
> useEffect(()=> {
>  if(state == null){
>     run();
>  }
> }, [])
> ```
> 
> This problem is more of an engineering problem, caused by the mechanism of useModel, not a general problem.
> 
> The useModel's model is initialized when the application mount, not when it is needed, which causes this problem.
> 
> If you use other solutions such as context, there will be no problem.
> 
> So this problem is not a general problem, ahooks should not have similar hooks.

There is no need to use useeffect, as you gave in the first example, when I call the data variable, if it is empty, it will send a request, otherwise it will fetch it from the state.

Why am I using useEffect? For example, if a page needs the state variable in the "A" model, first I have to use useEffect at the beginning of the page and say if it is empty, send the request, otherwise bring it from the state, and this leads to code duplication.

Even without the useModel hook, even a struct where I keep a normal state variable, throwing this request on every page that needs it is pointless code duplication.

For example,

```
Component StateProductModel.tsx
export const StateProductModel = () => {
  const [products, setProducts] = useState([]);
  
  const {run: getProducts} = useRequest(); // manuel true
  
  return {products, setProducts, getProducts}
}

Component Product.tsx
export const Product = () => {
  const {getProducts, products} = useModel('StateProductModel');
  
  useEffect(()=> {
    if(products.length === 0){
      getProducts();
    }
  }, [products.length, getProducts]);
  
  return (<>{products}</>)
}

Component ProductCategory.tsx
export const ProductCategory = () => {
  const {getProducts, products} = useModel('StateProductModel');
  
  useEffect(()=> {
    if(products.length === 0){
      getProducts();
    }
  }, [products.length, getProducts]);
  
  return (<>{products}</>)
}
```
What needs to happen is that when only products are requested without the need for getProducts and useEffect, all these operations are performed without duplication of code.


The code sample should be as follows.

```
Component StateProductModel.tsx
export const StateProductModel = () => {
// I don't know what mechanism could be here
const products = useReqState();

return {products}
}

Component Product.tsx
export const Product = () => {
  const {products} = useModel('StateProductModel');
 
  return (<>{products}</>)
}

Component ProductCategory.tsx
export const ProductCategory = () => {
  const { products} = useModel('StateProductModel');
 
  return (<>{products}</>)
}
```

**Comment by xXAvoraXx** [comment] 2022-03-11 11:29
> > I understand what you mean, but I don't have a good solution.
> > There have two problem:
> > 
> > 1. Multiple calls, only one request is actually sent, like this
> > 
> > ```
> > Child[0] rendering... -> result request to api.
> > Child[1] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
> > Child[2] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
> > Child[3] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
> > Child[4] rendering... -> A request has already been sent, skip sending the request, render again when the state is ready.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This can be resolved by useRequest **options.cacheKey**.
> > 
> > 2. Check whether it is empty before each use.
> > 
> > ```ts
> > const {state} = useModel('state');
> > useEffect(()=> {
> >  if(state == null){
> >     run();
> >  }
> > }, [])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This problem is more of an engineering problem, caused by the mechanism of useModel, not a general problem.
> > The useModel's model is initialized when the application mount, not when it is needed, which causes this problem.
> > If you use other solutions such as context, there will be no problem.
> > So this problem is not a general problem, ahooks should not have similar hooks.
> 
> There is no need to use useeffect, as you gave in the first example, when I call the data variable, if it is empty, it will send a request, otherwise it will fetch it from the state.
> 
> Why am I using useEffect? For example, if a page needs the state variable in the "A" model, first I have to use useEffect at the beginning of the page and say if it is empty, send the request, otherwise bring it from the state, and this leads to code duplication.
> 
> Even without the useModel hook, even a struct where I keep a normal state variable, throwing this request on every page that needs it is pointless code duplication.

For example,

```
Component StateProductModel.tsx
export const StateProductModel = () => {
  const [products, setProducts] = useState([]);
  
  const {run: getProducts} = useRequest(); // manuel true
  
  return {products, setProducts, getProducts}
}

Component Product.tsx
export const Product = () => {
  const {getProducts, products} = useModel('StateProductModel');
  
  useEffect(()=> {
    if(products.length === 0){
      getProducts();
    }
  }, [products.length, getProducts]);
  
  return (<>{products}</>)
}

Component ProductCategory.tsx
export const ProductCategory = () => {
  const {getProducts, products} = useModel('StateProductModel');
  
  useEffect(()=> {
    if(products.length === 0){
      getProducts();
    }
  }, [products.length, getProducts]);
  
  return (<>{products}</>)
}
```
What needs to happen is that when only products are requested without the need for getProducts and useEffect, all these operations are performed without duplication of code.

**Comment by xXAvoraXx** [comment] 2022-03-18 16:48
Is there any idea or update? or development?

**Comment by brickspert** [comment] 2022-03-22 06:33
> Is there any idea or update? or development?

I know what you mean, but ahooks won't provide this functionality for now.

It is recommended that you solve this problem in your own project first. When more users need this capability in the future, we will consider adding it to ahooks.

**Closed as completed** 2022-06-22 14:32 UTC
